spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: linlai
    username: root
    url: jdbc:mysql://8.136.136.248:3306/web01
    type: com.alibaba.druid.pool.DruidDataSource
########≈‰÷√redis###########
  redis:
    host: 8.136.136.248
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cll.demo.pojo
  configuration:
    map-underscore-to-camel-case: true
